version: 2.1

jobs:
  test:
    parameters:
      ruby:
        type: string
      rails:
        type: string
      postgres:
        type: string
    docker:
      - image: << parameters.ruby >>
        environment:
          BUNDLE_GEMFILE: gemfiles/<< parameters.rails >>.gemfile
      - image: cimg/<< parameters.postgres >>
        environment:
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - checkout
      - run: gem install bundler
      - run: bundle install
      - run: bundle exec rspec

workflows:
  all-tests:
    jobs:
      - test:
          matrix:
            parameters:
              ruby: ['ruby:3.2', 'ruby:3.3', 'ruby:3.4']
              rails: ['rails_7.1', 'rails_7.2', 'rails_8.0']
              postgres: ['postgres:13.16', 'postgres:14.13', 'postgres:15.8', 'postgres:16.4', 'postgres:17.0']
